#!/usr/bin/perl

package Rabaklib::Doc::Tutorial;

# This module is actually a script that generates all sample files in "./samples".

# It's POD file also can be used to generate a combined Tutorial:
# perldoc RabakLib::Doc::Tutorial;

use warnings;
use strict;

use Data::Dumper;

my $out_dir= ".";

our %part= ();
my $part;
my $partn= 1;
while (<DATA>) {
    if (/^=head1\s+(\S+)\s+(.*)/) {
        $part= substr($1, 0, 6) eq "SAMPLE" ? sprintf("%02d", $partn++) : $1;
        $part{$part}= [ $2, '' ];
        next;
    }
    $part{$part}[1] .= $_ if $part;
}

# print Dumper(\%part); die;

my $toc= @{ $part{'INTRO'} }[1];

sub expand_body {
    my $body= shift;
    my $n= shift;
    my $no_code= shift || 0;

    $body =~ s/^\s+\n|\n\s+$//gs;

    my $state= 0;
    my $contents= "";
    for (split(/\n/, $body)) {
        my ($indent, $line)= ($1, $2) if /^(\s*)(.*)/;

        if ($no_code || $state == 2 || (!$indent && $line)) {

            $state= 2 if $state == 1;

            if (/^=head\d\s+(.*)/) {
                $contents .= "#\n"
                    . "# $1\n"
                    . "# " . ("-" x length($1)) . "\n";
                next;
            }
            next if /^=/;
            s/ample\d/ample$n/g;
            $contents .= "# $_\n";
            next;
        }
        next if /^=/;
        if (!$line) {
            $contents .= "\n";
            next;
        }
        $line =~ s/ample\d/ample$n/g;
        $indent =~ s/^\s\s//;

        # Decrease original indentiation by two
        $indent =~ s/^\s\s\s\s/  /;
        $contents .= "$indent$line\n";
        $state= 1 if $state == 0;
    }
    return $contents;
}

for my $n (sort { $a cmp $b } keys %part) {

    next if $n =~ /[^\d]/;

    my ($title, $body)= @{ $part{$n} };

    $toc .= "rabak.sample$n.cf: $title\n";
    $title= "Sample $n: $title";

    my $contents=
        expand_body(@{ $part{'COMMON_HEAD'} }[1], $n)
        . "\n\n"
        . "#" x length($title) . "######\n"
        . "#  $title  #\n"
        . "#" x length($title) . "######\n"
        . expand_body($body, $n)
        . expand_body(@{ $part{'COMMON_TAIL'} }[1], $n, 1)
    ;

    my $fout;
    open $fout, ">$out_dir/rabak.sample$n.cf" or die "Can't write rabak.sample$n.cf";
    print $fout $contents;
    close $fout;
}

# Remove old samples
while (-e "$out_dir/rabak.sample$partn.cf") {
    unlink "$out_dir/rabak.sample$partn.cf";
    $partn++;
}

my $fout;
open $fout, ">$out_dir/TABLE_OF_CONTENTS" or die "Can't write TABLE_OF_CONTENTS";
print $fout $toc;
close $fout;

__DATA__


=head1 INTRO

The sample files build on one another. If you don't understand a certain feature,
please look at the previous example.


=begin EXTRA


=head1 COMMON_HEAD

=head2 Annotated rabak sample configuration file

These configuration values are common to all samples:

  switch.verbose = 1
  switch.logging = 1


=head1 COMMON_TAIL

=head2 Further information

For more documentation, try 'rabak doc'.

To find out how b<rabak> sees this file, type '../rabak -c rabak.sample1.cf conf'.

(This file was generated by RabakLib::Doc::Tutorial.
Changes to this file are useless.
To read the whole tutorial in one file, type 'rabak tutorial'.)


=end EXTRA


=head1 SAMPLE1: Quick start! A Minimal Configuration

  sample.title = Sample1
  sample.source = samples/source
  sample.target = samples/target


=head2 Explanation

Running
  ../rabak -c rabak.sample1.cf conf
will produce following output:

  Available backup sets in "samples/rabak.sample1.cf":
    sample - Sample1, backs up "samples/source" to "samples/target"

b<Rabak> sees one backup set named 'sample', which will backup all files
from the directory 'samples/source' into the directory 'samples/target'.

Try this by running
  ../rabak -c rabak.sample1.cf backup sample

This will result in something like following output:
  INFO:    Rabak Version 0.6rc4
  INFO:    Backing up source '&source'
  INFO:    Backup start at 2007-07-30 18:01:30: sample, 2007-07-30, Sample1
  INFO:    Running: rsync -a --hard-links --filter=". /tmp/fSmfte1Dwk" --stats --verbose
                        "(some path)/samples/source/" "(some path)/samples/target/2007-07.sample/2007-07-30"

You'll find your backup in 'samples/target/2007-07.sample/2007-07-30'.


=head1 SAMPLE1: Excluding specific files

  sample.title = Sample1
  sample.source = samples/source
  sample.target = samples/target
  sample.exclude = *.bak *.~

TBD!


=head1 SAMPLE1: Multiple Backup Sets; Variables Basics

  target_path= samples/target

  exclude_files=
        *.bak
        *.~

  exclude= $exclude_files /tmp

  sample_full.title = Full Backup
  sample_full.source = samples/source
  sample_full.target = $target_path
  sample_full.exclude = $exclude

  sample_home.title = Backup Home Directory
  sample_home.source = samples/source/home/user1
  sample_home.target = $target_path
  sample_home.exclude = $exclude

Variables are defined in a simple 'key=value' manner.
Here, 'target_path' is assigned the value 'samples/target'.

The 'exclude_files' value has a multi-line assignment.
An expression may be extended across multiple lines by indenting them.
The result is equal to 'exclude= *.bak *.~' but has an increased legibility.

Finally, the 'exclude' value uses the 'exclude_files' value, the result being
the same as 'exclude= *.bak *.~ /tmp'.

TBD!


=head1 SAMPLE1: Simple Mount Points

  target_base = samples/target

  mount1.device = /dev/sda1
  mount1.directory = $target_base
  mount1.unmount = 1

  mount2.device = /dev/sdb1
  mount2.directory = $target_base
  mount2.unmount = 1

  # Backup set "Sample1 A"

  sample1_a.title = Sample1 A
  sample1_a.source.path = samples/source
  sample1_a.target.path = samples/target
  sample1_a.target.mount = &mount1

  # Backup set "Sample1 B"

  sample1_b.title = Sample1 B
  sample1_b.source.path = samples/source
  sample1_b.target.path = samples/target
  sample1_b.target.mount = &mount1 &mount2

TBD!


=head1 SAMPLE1: Include Files; Target Groups

  target_base = samples/target

  INCLUDE ../rabak.std.cf

  mount1.device = /dev/sda[1-4]
  mount1.directory = $target_base
  mount1.unmount = 1

  sample.title = Sample1
  sample.source.path = samples/source
  sample.target.path = samples/target
  sample.target.mount = &mount1
  sample.target.group = day-of-week
  sample.exclude = *.bak *.~

TBD!


=head1 SAMPLE1: Backing up databases

  switch.pretend = 1
  sample_target = samples/target

  # Some external device

  mount_external.device= /dev/sda1
  mount_external.directory= /mnt/external

  # Postgresql Database

  sample_pg.title = Databases of sample
  sample_pg.source.path = pgsql://vbulletin,postnuke
  sample_pg.source.user = *default*
  sample_pg.source.password = secret
  sample_pg.target = $sample_target
  #sample_pg.target.path = $target_base/postgres
  sample_pg.keep = 3

  # MySql Database

  sample_mysql.title = Mysql-DBs
  sample_mysql.source.path = mysql://*
  sample_mysql.source.user = mysql_user
  sample_mysql.source.password = secret
  sample_mysql.source.mount = &mount_external
  sample_mysql.target = $sample_target
  #sample_mysql.target.path = $target_base/mysql
  sample_mysql.keep = 3

TBD!


=head1 SAMPLE1: Multiple Sources per Backup Set

TBD!


=head1 SAMPLE1: Unsing a Samba Mount Point as Source

  smb_dir = /mnt/samba/e
  smb_user= backup
  smb_password = secret

  # If you want to leave this configuration file readable for others, you can put
  # passwords in a different file and include it. E.g.: contents rabak.secret.cf:
  # smb_password = secret
  #
  # Then, to include rabak.secret.cf add the following line to this file:
  # INCLUDE rabak.secret.cf

  mount_smb_server.type= cifs
  mount_smb_server.device= //smb_server/e$
  mount_smb_server.directory= $smb_dir
  mount_smb_server.opts= "username=$smb_user,password=$smb_password,ro"
  mount_smb_server.unmount= 1

  sample_target.path = samples/target

  sample.title = Gesamtsystem
  sample.source.path = samples/source
  sample.target = &sample_target
  sample.mount = &mount_smb_server


=head1 SAMPLE1: Backup from remote to local

TBD!


=head1 SAMPLE1: Backup from local to remote

To backup to a remote target, you must provide two additional information to the target object: user and host.
B<rabak> at the moment supports key authentification, so you may have to add a authorised key on the target machine.
User/password support is tricky because you can't supply a password to ssh because of security reasons.

Once you have a working key authentification, you can specify the same variables to remote targets as to local targets.
For example, you can specify mount points, and rabak will do the right thing.

  # Setup local source
  sample_local_source.path = samples/source

  # Setup remote target
  sample_remote_target.path = $target_dir
  sample_remote_target.host = some.host.name
  sample_remote_target.user = username.on.host
  sample_remote_target.mount.device = /dev/dev.on.remote.host
  sample_remote_target.mount.device = /mnt/path/on.remote.host
  sample_remote_target.mount.umount = 1

  # specify a LOCAL directory to temporarily store files for the remote system (eg. database dumps)
  sample_remote_target.tempdir = /path/for/temporary/files/on.local.host
  sample_remote_target.group = sample
  sample_remote_target.discfree_threshold = 10%

  sample.title = From local to remote
  sample.source = &sample_local_source
  sample.target = &sample_remote_target


=head1 SAMPLE1: Backup from remote to remote

Remote to remote backup is essentially the same to local to remote.
Just specify an user and a host for the source and the target object and you're done.

  # Setup local source
  sample_remote_source.path = /home/
  sample_remote_source.host = some.host.name
  sample_remote_source.user = username.on.host

  # Setup remote target
  sample_remote_target.path = /rabak
  sample_remote_target.host = some.host.name
  sample_remote_target.user = username.on.host
  sample_remote_target.mount.device = /dev/dev.on.remote.host
  sample_remote_target.mount.device = /mnt/path/on.remote.host
  sample_remote_target.mount.umount = 1

  # specify a LOCAL directory to temporarily store files for the remote system (eg. database dumps)
  sample_remote_target.tempdir = /path/for/temporary/files/on.local.host
  sample_remote_target.group = sample
  sample_remote_target.discfree_threshold = 10%

  sample.title = From remote to remote
  sample.source = &sample_remote_source
  sample.target = &sample_remote_target


=head1 SAMPLE1: Variables in depth

Variables are defined in a simple 'key=value' manner. E.g., the code

  server1= lisa

assigns the string 'lisa' to the variable 'server1'.

Variables can be clustered in objects simply by adding a name and a
dot in front of a variable name. Examples:

=over

=item Sample A

  mount1.title= My Mount Point
  mount1.path= /mnt/data

  lisa.title= Server "Lisa"
  lisa.mount_data.title= One of Lisa's Mount Points
  lisa.mount_data.path= /mnt/data

=back

Here, 'mount1' and 'lisa.mount1' are objects that contain simple variables.
'lisa' is an object containing a variable 'title' and an object 'mount_data'.

There are two ways in using a variable: substitution or binding.
Here are examples for substitution:

=over

=item Sample A, continued

  mount2= $mount1
  mount2.title= Copy of the "mount1" Mount Point

  bart.title= Server "Bart"
  bart.mount_data= $lisa.mount_data
  bart.mount_data.title= Now it's Bart's Mount Point

=back

The b<$>-Sign followed by a variable name is substituted by the value of that variable.
The above assignments will result in the following values:

  mount2.title= Copy of the "mount1" Mount Point
  mount2.path= /mnt/data

  bart.title= Server "Bart"
  bart.mount_data.title= Now it's Bart's Mount Point
  bart.mount_data.path= /mnt/data

Binding: TBD

Variables with a b<&> sigil are "bound variabled" and treated differently.
They act more than references and are assigned at time of use.
The idea is that you can set up a variable with a reference to anonther variable that is defined later in the configuration file.
This is mostly useful for common setups that are put into include-files.
It was actually introduced to support "std_exclude = &exclude", allowing the user to define "exclude" later on.
So, the standard include file needs it, you probably won't need it often.

=over

=item Sample B

  b.x = 1
  b.y = 2

  a = $b
  a.z= 3

  # c = &b
  # c.z= 3      # Won't work!

=back

TBD!

=head2 EOF
