#!/usr/bin/perl

use warnings;
use strict;

print "# THIS IS A CONVENIENCE WRAPPER FOR THE RABAK SCRIPT.\n";

my $sCmd= "";
my $bFoundC= "";
map {
    $_= "samples/$_" if $bFoundC;
    $bFoundC= $_ eq '-c';
    $sCmd .= " \"$_\"";
} @ARGV;

chdir "..";
exec "./rabak $sCmd";
