#!/usr/bin/perl

package Rabaklib::Doc::Tutorial;

# This module is actually a script that generates all sample files in "/samples".

# It's POD file also can be used to generate a combined Tutorial:
# perldoc RabakLib::Doc::Tutorial;

use warnings;
use strict;

use Data::Dumper;

my $out_dir= ".";

our %part= ();
my $part;
my $partn= 1;
while (<DATA>) {
    if (/^=head1\s+(\S+)\s+(.*)/) {
        $part= substr($1, 0, 6) eq "SAMPLE" ? sprintf("%02d", $partn++) : $1;
        $part{$part}= [ $2, '' ];
        next;
    }
    $part{$part}[1] .= $_ if $part;
}

my $toc= @{ $part{'INTRO'} }[1];

sub expand_body {
    my $body= shift;
    my $n= shift;
    my $no_code= shift || 0;

    $body =~ s/^\s+\n|\n\s+$//gs;

    my $state= 0;
    my $contents= "";
    for (split(/\n/, $body)) {
        my ($indent, $line)= ($1, $2) if /^(\s*)(.*)/;

        if ($no_code || $state == 2 || (!$indent && $line)) {
            $state= 2 if $state == 1;
            if (/^=head\d\s+(.*)/) {
                $contents .= "#\n"
                    . "# $1\n"
                    . "# " . ("-" x length($1)) . "\n";
                next;
            }
            next if /^=/;
            s/ample\d/ample$n/g;
            $contents .= "# $_\n";
            next;
        }
        next if /^=/;
        if (!$line) {
            $contents .= "\n";
            next;
        }
        $line =~ s/ample\d/ample$n/g;
        $indent =~ s/^\s\s//;

        # Decrease original indentiation by two
        $indent =~ s/^\s\s\s\s/  /;
        $contents .= "$indent$line\n";
        $state= 1 if $state == 0;
    }
    return $contents;
}

for my $n (sort { $a cmp $b } keys %part) {

    next if $n =~ /[^\d]/;

    my ($title, $body)= @{ $part{$n} };

    $toc .= "rabak.sample$n.cf: $title\n";
    $title= "Sample $n: $title";

    my $contents=
        expand_body(@{ $part{'COMMON_HEAD'} }[1], $n)
        . "\n\n"
        . "#" x length($title) . "######\n"
        . "#  $title  #\n"
        . "#" x length($title) . "######\n"
        . expand_body($body, $n)
        . expand_body(@{ $part{'COMMON_TAIL'} }[1], $n, 1)
    ;

    my $fout;
    open $fout, ">$out_dir/rabak.sample$n.cf" or die "Can't write rabak.sample$n.cf";
    print $fout $contents;
    close $fout;
}

# Remove old samples
while (-e "$out_dir/rabak.sample$partn.cf") {
    unlink "$out_dir/rabak.sample$partn.cf";
    $partn++;
}

my $fout;
open $fout, ">$out_dir/TABLE_OF_CONTENTS" or die "Can't write TABLE_OF_CONTENTS";
print $fout $toc;
close $fout;

__DATA__


=head1 INTRO

The sample files build on one another. If you don't understand a certain feature,
please look at the previous example.


=begin EXTRA


=head1 COMMON_HEAD

=head2 Annotated rabak sample configuration file

These configuration values are common to all samples:

  switch.verbose = 1
  switch.logging = 1


=head1 COMMON_TAIL

=head2 Further information

For more documentation, try 'rabak doc'.

To find out how b<rabak> sees this file, type '../rabak -c rabak.sample1.cf conf'.

(This file was generated by RabakLib::Doc::Tutorial.
Changes to this file are useless.
To read the whole tutorial in one file, type 'rabak tutorial'.)


=end EXTRA


=head1 SAMPLE1: Quick start! A Minimal Configuration

  sample.title = Sample1
  sample.source = sample-source
  sample.target = sample-target


=head2 Explanation

Running
  ../rabak -c rabak.sample1.cf conf
will produce following output:

  Available backup sets in "rabak.sample1.cf":
    sample - Sample1, backs up "sample-source" to "sample-target"

b<Rabak> sees one backup set named 'sample', which will backup all files
from the directory 'sample-source' into the directory 'sample-target'.

Try this by running
  ../rabak -c rabak.sample1.cf backup

This will result in something like following output:
  INFO:    Rabak Version 0.6rc4
  INFO:    Backing up source '&source'
  INFO:    Backup start at 2007-07-30 18:01:30: sample, 2007-07-30, Sample1
  INFO:    Running: rsync -a --hard-links --filter=". /tmp/fSmfte1Dwk" --stats --verbose
                        "(some path)/samples/sample-source/" "(some path)/samples/sample-target/2007-07.sample/2007-07-30.sample-source"

You'll find your backup in 'samples/sample-target/2007-07.sample/2007-07-30.sample-source'.

TODO: Pfade korrigieren


=head1 SAMPLE1: Excluding specific files

  sample.title = Sample1
  sample.source = sample-source
  sample.target = sample-target
  sample.exclude = *.bak *.~

TBD!


=head1 SAMPLE1: Multiple Backup Sets; Variables Basics

  target_path= sample-target

  exclude_files=
        *.bak
        *.~

  exclude= $exclude_files /tmp

  sample_full.title = Full Backup
  sample_full.source = sample-source
  sample_full.target = $target_path
  sample_full.exclude = $exclude

  sample_home.title = Backup Home Directory
  sample_home.source = sample-source/home/user1
  sample_home.target = $target_path
  sample_home.exclude = $exclude

Variables are defined in a simple 'key=value' manner.
Here, 'target_path' is assigned the value 'sample-target'.

The 'exclude_files' value has a multi-line assignment.
An expression may be extended across multiple lines by indenting them.
The result is equal to 'exclude= *.bak *.~' but has an increased legibility.

Finally, the 'exclude' value uses the 'exclude_files' value, the result being
the same as 'exclude= *.bak *.~ /tmp'.

TBD!


=head1 SAMPLE1: Simple Mount Points

  target_base = sample-target

  mount1.device = /dev/sda1
  mount1.directory = $target_base
  mount1.unmount = 1

  mount2.device = /dev/sdb1
  mount2.directory = $target_base
  mount2.unmount = 1

  # Backup set "Sample1 A"

  sample1_a.title = Sample1 A
  sample1_a.source.path = sample-source
  sample1_a.target.path = sample-target
  sample1_a.target.mount = &mount1

  # Backup set "Sample1 B"

  sample1_b.title = Sample1 B
  sample1_b.source.path = sample-source
  sample1_b.target.path = sample-target
  sample1_b.target.mount = &mount1 &mount2

TBD!


=head1 SAMPLE1: Include Files; Target Groups

  target_base = sample-target

  INCLUDE ../rabak.std.cf

  mount1.device = /dev/sda[1-4]
  mount1.directory = $target_base
  mount1.unmount = 1

  sample.title = Sample1
  sample.source.path = sample-source
  sample.target.path = sample-target
  sample.target.mount = &mount1
  sample.target.group = day-of-week
  sample.exclude = *.bak *.~

TBD!


=head1 SAMPLE1: Backing up databases

  switch.pretend = 1

  # Postgresql Database

  sample_pg.title = Databases of sample
  sample_pg.source = pgsql:vbulletin,postnuke
  sample_pg.target = $sample_target
  sample_pg.target.path = $target_base/postgres
  sample_pg.user = *default*
  sample_pg.password = secret
  sample_pg.keep = 3

  # MySql Database

  sample_mysql.title = Mysql-DBs
  sample_mysql.source = mysql:*
  sample_mysql.target = $sample_target
  sample_mysql.target.path = $target_base/mysql
  sample_mysql.user = $mysql_user
  sample_mysql.password = $mysql_password
  sample_mysql.keep = 3
  sample_mysql.mount = &mount_external

TBD!


=head1 SAMPLE1: Multiple Sources per Backup Set

TBD!


=head1 SAMPLE1: Unsing a Samba Mount Point as Source

  smb_dir = /mnt/samba/e
  smb_user= backup
  smb_password = secret

  # If you want to leave this configuration file readable for others, you can put
  # passwords in a different file and include it. E.g.: contents rabak.secret.cf:
  # smb_password = secret
  #
  # Then, to include rabak.secret.cf add the following line to this file:
  # INCLUDE rabak.secret.cf

  mount_smb_server.type= cifs
  mount_smb_server.device= //smb_server/e$
  mount_smb_server.directory= $smb_dir
  mount_smb_server.opts= "username=$smb_user,password=$smb_password,ro"
  mount_smb_server.unmount= 1

  sample_target.path = sample-target

  sample.title = Gesamtsystem
  sample.source.path = sample-source
  sample.target = &sample_target
  sample.mount = &mount_smb_server


=head1 SAMPLE1: Backup from remote to local

TBD!


=head1 SAMPLE1: Backup from local to remote

TBD!

  sample_remote_target.path = $target_dir
  sample_remote_target.host = some.host.name
  sample_remote_target.user = username.on.host
  sample_remote_target.mount.device = /dev/dev.on.remote.host
  sample_remote_target.mount.device = /mnt/path/on.remote.host
  sample_remote_target.mount.umount = 1

  # specify a LOCAL directory to temporarily store files for the remote system (eg. database dumps)
  sample_remote_target.tempdir = /path/for/temporary/files/on.local.host
  sample_remote_target.group = sample
  sample_remote_target.discfree_threshold = 10%


=head1 SAMPLE1: Backup from remote to remote

TBD!


=head1 SAMPLE1: Variables in depth

  b.x = 1
  b.y = 2
  a = &b
  a.z= 3

  c = $b
  c.z= 3

TBD!

=head2 EOF
