#!/bin/sh

# Produces a test environment. You can easily get rid of it again
# with the testdev-remove script.

BASEDIR="/tmp/rabak-sample-data"

if which losetup >/dev/null 2>&1; then
    dummy=""
else
    echo "you have to be root to create dummy devices (losetup not found in path)"
    exit
fi

function mk_target {
    DEVI="$1"
    DEVN="$2"

    dd if=/dev/zero of="$BASEDIR/dev_$DEVN" count=3000
    mknod "$BASEDIR/dev.$DEVN" b 7 $DEVI
    losetup "$BASEDIR/dev.$DEVN" "$BASEDIR/dev_$DEVN"
    mkfs -t ext2 -N 1000 "$BASEDIR/dev.$DEVN"

    mkdir "$BASEDIR/mnt_$DEVN"
    mount "$BASEDIR/dev.$DEVN" "$BASEDIR/mnt_$DEVN"
}

mk_target "0" "loop0"
mkdir "$BASEDIR/mnt_loop0/rabak"
echo "targetvalues = dayofweek.Mon dayofweek.Wed dayofweek.Fri" >  "$BASEDIR/mnt_loop0/rabak.dev.cf"
umount "$BASEDIR/mnt_loop0"

mk_target "1" "loop1"
mkdir "$BASEDIR/mnt_loop1/rabak"
echo "targetvalues = dayofweek.Tue dayofweek.Thu dayofweek.Sat" >  "$BASEDIR/mnt_loop1/rabak.dev.cf"
umount "$BASEDIR/mnt_loop1"

mk_target "2" "source"
echo "some data" >  "$BASEDIR/mnt_source/data.txt"
umount "$BASEDIR/mnt_source"

mkdir "$BASEDIR/mnt_target"
